import base64
from PIL import Image
import io
import os

# Open the image generated by the AI
img_path = "/Users/bitanbiswas/.gemini/antigravity/brain/7801b942-32ca-46e3-aee4-792673f45c28/holi_cert_borderless_premium_1773156264221.png"
if not os.path.exists(img_path):
    print("Image not found:", img_path)
    exit(1)

img = Image.open(img_path)
# Resize for A4 landscape at roughly 100 dpi to prevent massive base64 strings
img = img.resize((1056, 746), Image.Resampling.LANCZOS)
buffer = io.BytesIO()
# Convert to RGB if it has alpha
if img.mode in ('RGBA', 'P'):
    img = img.convert('RGB')
img.save(buffer, format="JPEG", quality=75)
b64_str = base64.b64encode(buffer.getvalue()).decode("utf-8")
img_data_uri = f"data:image/jpeg;base64,{b64_str}"

html_content = f"""<!DOCTYPE html>
<html lang="bn">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>আবার বসন্ত ২০২৬ - প্রশস্তিকা</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+Bengali:wght@400;600;700;900&family=Noto+Sans+Bengali:wght@400;500;600;700&display=swap" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<style>
  @page {{
    size: 297mm 210mm landscape;
    margin: 0;
  }}
  body {{
    margin: 0;
    padding: 40px 0;
    background-color: #2c2c2c;
    display: flex;
    flex-direction: column;
    align-items: center;
    font-family: 'Noto Sans Bengali', sans-serif;
  }}
  .scale-wrapper {{
    /* Using a wrapper to scale the fixed size certificate to fit on smaller screens */
    width: 1587px;
    height: 1123px;
    transform-origin: top center;
  }}
  #certificate {{
    width: 1587px;
    height: 1123px;
    position: relative;
    background-color: #fffaf0;
    overflow: hidden;
    /* 4-Layer Border System Applied Here */
    /* html2canvas struggles with border-image linear gradients, so we use multiple box-shadows to simulate the outermost and innermost borders perfectly for export */
    box-shadow: inset 0 0 0 8px #d4a017, inset 0 0 0 12px #fffaf0, inset 0 0 0 14px #c8960c, inset 0 0 25px 14px rgba(0,0,0,0.15), 0 15px 50px rgba(0,0,0,0.5);
    box-sizing: border-box;
  }}

  /* We removed the absolute border-layers because inset box-shadow on #certificate now handles the entire 4-layer luxury frame robustly for html2canvas */
  
  /* Corner Ornaments */
  .corner-ornament {{
    position: absolute;
    font-family: serif;
    font-size: 32px;
    color: #c8960c;
    z-index: 15;
    line-height: 1;
  }}
  .corner-tl {{ top: 12px; left: 16px; }}
  .corner-tr {{ top: 12px; right: 16px; }}
  .corner-bl {{ bottom: 12px; left: 16px; }}
  .corner-br {{ bottom: 12px; right: 16px; }}

  /* Background Visuals */
  .bg-image {{
    position: absolute;
    inset: 0;
    background-image: url("{img_data_uri}");
    background-size: cover;
    background-position: center;
    z-index: 1;
  }}
  .bg-vignette {{
    position: absolute;
    inset: 0;
    /* Expanding the bright center so text has more breathing room, fading out smoother into the edges */
    background: radial-gradient(ellipse 75% 65% at 50% 50%, rgba(255,250,240,0.95) 0%, rgba(255,250,240,0.85) 45%, rgba(255,250,240,0.4) 80%, transparent 100%);
    z-index: 2;
  }}

  /* Content Layout */
  .cert-content {{
    position: relative;
    z-index: 20;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    height: 100%;
    /* Mapping 14mm 22mm 12mm 22mm to pixels at 144dpi (~ 80px 125px 68px 125px) */
    padding: 80px 125px 68px 125px;
    box-sizing: border-box;
  }}

  /* Section 1: Header */
  .header-block {{
    text-align: center;
    margin-top: 10px;
  }}
  .main-title {{
    font-family: 'Noto Serif Bengali', serif;
    font-weight: 900;
    font-size: 64pt;
    color: #7a0030;
    margin: 0;
    line-height: 1.2;
    letter-spacing: normal; /* Force html2canvas to not squish kerning */
    text-rendering: optimizeLegibility;
    text-shadow: 0 4px 15px rgba(255,250,240,0.95), 0 2px 5px rgba(0,0,0,0.2);
  }}
  .sub-title {{
    font-family: 'Noto Serif Bengali', serif;
    font-weight: 700;
    font-size: 32pt;
    color: #1e4d00;
    margin: 12px 0 8px 0;
    letter-spacing: 1px;
    text-shadow: 0 2px 10px rgba(255,250,240,0.9);
  }}
  .organizer {{
    font-family: 'Noto Sans Bengali', sans-serif;
    font-weight: 600;
    font-size: 16pt;
    color: #3a1500;
    margin: 0;
    letter-spacing: normal;
    text-shadow: 0 1px 5px rgba(255,250,240,1);
  }}

  /* Section 2: Gold Divider */
  .gold-divider {{
    width: 65%;
    height: 2px;
    margin: 0 auto;
    background: linear-gradient(to right, transparent, #f5d060, #c8960c, #f5d060, transparent);
    box-shadow: 0 0 10px rgba(200,150,12,0.5);
  }}

  /* Section 3: Prashastika Badge */
  .badge-wrapper {{
    text-align: center;
  }}
  .badge {{
    display: inline-block;
    border: 2px solid #c8960c;
    border-radius: 50px;
    background: #fffdf5; /* Solid fallback for frosted glass to prevent html2canvas artifacts */
    font-family: 'Noto Serif Bengali', serif;
    font-weight: 800;
    font-size: 36pt;
    color: #7a0030;
    letter-spacing: normal;
    padding: 16px 80px;
    box-shadow: 0 8px 25px rgba(200,150,12,0.25);
  }}

  /* Section 4: Body Text box */
  .body-text-box {{
    /* Completely removed background and bordering for perfectly transparent, floating text */
    padding: 18px 30px;
    text-align: center;
    font-family: 'Noto Sans Bengali', sans-serif;
    font-weight: 600; 
    font-size: 20pt; 
    color: #120808;
    line-height: 2.4;
    margin: 0 auto;
    width: 95%;
    letter-spacing: normal;
    text-rendering: optimizeLegibility;
    text-shadow: 0 2px 10px rgba(255,250,240,0.95);
  }}
  .blank {{
    display: inline-block;
    border-bottom: 1.8px solid #3a1500;
    transform: translateY(2px);
  }}

  /* Section 5: Date & Place */
  .date-place {{
    display: flex;
    justify-content: space-between;
    width: 75%; /* Wider to feel more natural and spacious */
    margin: 0 auto; /* Centered block */
    font-family: 'Noto Sans Bengali', sans-serif;
    font-weight: 700;
    font-size: 16pt;
    color: #3a1500;
    text-shadow: 0 1px 5px rgba(255,250,240,1);
  }}

  /* Section 6: Signatures */
  .signature-block {{
    display: flex;
    justify-content: space-between;
    width: 100%;
    margin-bottom: 30px;
  }}
  .sig-col {{
    display: flex;
    flex-direction: column;
    align-items: center;
  }}
  .sig-line {{
    width: 140px; /* Longer signature lines look more premium */
    border-top: 2px solid #5a2800;
    margin-bottom: 12px;
  }}
  .sig-role {{
    font-family: 'Noto Sans Bengali', sans-serif;
    font-weight: 700;
    font-size: 18pt;
    color: #7a0030;
    letter-spacing: normal;
    text-shadow: 0 2px 8px rgba(255,250,240,0.9);
  }}

  /* Download Button outside */
  #downloadBtn {{
    background: linear-gradient(135deg, #c8960c, #f5d060, #c8960c);
    color: #3a1500;
    font-family: 'Noto Sans Bengali', sans-serif;
    font-size: 14pt;
    font-weight: 700;
    padding: 14px 48px;
    border: none;
    border-radius: 50px;
    cursor: pointer;
    box-shadow: 0 6px 24px rgba(200,150,12,0.4);
    margin-top: 28px;
    letter-spacing: 1px;
    transition: transform 0.2s, box-shadow 0.2s;
    z-index: 100;
  }}
  #downloadBtn:hover {{
    transform: scale(1.04);
    box-shadow: 0 8px 30px rgba(200,150,12,0.6);
  }}

  /* Print Media Query */
  @media print {{
    body {{ background: none; padding: 0; }}
    #downloadBtn {{ display: none; }}
    .scale-wrapper {{ transform: none !important; width: 297mm; height: 210mm; }}
    #certificate {{ width: 297mm; height: 210mm; box-shadow: none; }}
  }}
</style>
</head>
<body>

  <div class="scale-wrapper" id="scaleWrapper">
    <div id="certificate">
      <!-- Backgrounds -->
      <div class="bg-image"></div>
      <div class="bg-vignette"></div>

      <!-- No extra border layers needed, handled by #certificate box-shadow for perfect html2canvas export -->
      
      <!-- Corner Ornaments ❧ -->
      <div class="corner-ornament corner-tl">❧</div>
      <div class="corner-ornament corner-tr">❧</div>
      <div class="corner-ornament corner-bl">❧</div>
      <div class="corner-ornament corner-br">❧</div>

      <!-- Content -->
      <div class="cert-content">
        
        <!-- 1. Header -->
        <div class="header-block">
          <div class="main-title">আবার বসন্ত, ২০২৬</div>
          <div class="sub-title">অঙ্কন প্রতিযোগিতা</div>
          <div class="organizer">পরিচালনায়: ১৬ নম্বর ওয়ার্ড বসন্ত উৎসব কমিটি</div>
        </div>

        <!-- 2. Divider -->
        <div class="gold-divider"></div>

        <!-- 3. Badge -->
        <div class="badge-wrapper">
          <div class="badge">প্রশস্তিকা</div>
        </div>

        <!-- 4. Body Text -->
        <div class="body-text-box">
          <span class="blank" style="min-width: 80px;"></span> প্রতিযোগিতায় <span class="blank" style="min-width: 100px;"></span> বিভাগে <span class="blank" style="min-width: 80px;"></span> স্থানাধিকারী<br>
          শ্রী/শ্রীমতী <span class="blank" style="min-width: 340px;"></span> কে প্রশস্তিকা প্রদত্ত হল।
        </div>

        <!-- 5. Date & Place -->
        <div class="date-place">
          <div>তারিখ: <span class="blank" style="min-width: 140px;"></span></div>
          <div>স্থান: <span class="blank" style="min-width: 140px;"></span></div>
        </div>

        <!-- 6. Signatures -->
        <div class="signature-block">
          <div class="sig-col">
            <div class="sig-line"></div>
            <div class="sig-role">সভাপতি</div>
          </div>
          <div class="sig-col">
            <div class="sig-line"></div>
            <div class="sig-role">সম্পাদক</div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <button id="downloadBtn">Download Certificate (PNG)</button>

  <script>
    // Scale the wrapper to fit nicely on the user's screen
    function resizeCertificate() {{
      const wrapper = document.getElementById('scaleWrapper');
      const windowWidth = window.innerWidth;
      const windowHeight = window.innerHeight;
      // We want to fit 1587px width into the window with some padding
      const scaleX = (windowWidth - 40) / 1587;
      const scaleY = (windowHeight - 120) / 1123;
      const scale = Math.min(scaleX, scaleY, 1); // Cap at 1 (no upscaling)
      wrapper.style.transform = `scale(${{scale}})`;
      // Adjust margin so button placement stays tight
      wrapper.style.marginBottom = `-${{1123 * (1 - scale)}}px`;
    }}
    
    window.addEventListener('resize', resizeCertificate);
    resizeCertificate(); // initial call

    // Download Logic
    document.getElementById('downloadBtn').addEventListener('click', async () => {{
      const btn = document.getElementById('downloadBtn');
      const originalText = btn.innerText;
      btn.innerText = "Generating PNG... (This may take a moment)";
      btn.style.opacity = "0.7";
      btn.style.pointerEvents = "none";

      try {{
        const cert = document.getElementById('certificate');
        
        // Wait for fonts to load completely to avoid squishing
        await document.fonts.ready;
        // Additional micro-delay ensures CSS rendering is totally finished repainting
        await new Promise(resolve => setTimeout(resolve, 300));

        const canvas = await html2canvas(cert, {{
          scale: 4,           // 4x resolution
          useCORS: true,
          backgroundColor: null,
          logging: false,
          letterRendering: 1, // Forces explicit coordinate drawing for text to stop squishing
          onclone: function(clonedDoc) {{
            // CRITICAL FIX: Temporarily remove the CSS scale transform on the cloned document inside html2canvas 
            // before rendering, otherwise it exports a tiny, garbled, squashed image!
            const scaleWrap = clonedDoc.getElementById('scaleWrapper');
            if (scaleWrap) {{
              scaleWrap.style.transform = 'none';
              scaleWrap.style.marginBottom = '0';
            }}
          }}
        }});
        
        const link = document.createElement('a');
        link.download = 'prashastika_certificate.png';
        link.href = canvas.toDataURL('image/png', 1.0);
        link.click();
      }} catch (err) {{
        console.error("Error generating image:", err);
        alert("There was an error generating the PNG. Please check the console.");
      }} finally {{
        btn.innerText = originalText;
        btn.style.opacity = "1";
        btn.style.pointerEvents = "auto";
      }}
    }});
  </script>
</body>
</html>
"""

# Write HTML content to the file
output_path = "/Users/bitanbiswas/Documents/Antigravety Projects/Holi Drawing Certificate/certificate.html"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"File successfully created: {output_path}")
print(f"Total HTML string size is {len(html_content)} characters.")
